### ISSUE TITLE
sequence id different for selected sequences in fasta and metadata 

### ISSUE THREAD

**Issue by irinak128** [baymlab/wastewater_analysis#5]
with current scripts selected sequences have ids in metadata file as

hCoV-19/USA/IL-S21WGS2069/2021
hCoV-19/USA/NE-NCOV21-22435/2021
hCoV-19/USA/KS-KHEL-2191/2021
hCoV-19/USA/KS-KHEL-2193/2021
hCoV-19/USA/KS-KHEL-2190/2021

but corresponding sequence headers in selected sequences.fasta file look like

>hCoV-19/USA/IL-S21WGS2069/2021|2021-06-01|2021-06-04
>hCoV-19/USA/NE-NCOV21-22435/2021|2021-06-03|2021-06-07
>hCoV-19/USA/KS-KHEL-2191/2021|2021-06-01|2021-06-07
>hCoV-19/USA/KS-KHEL-2193/2021|2021-06-02|2021-06-07
>hCoV-19/USA/KS-KHEL-2190/2021|2021-06-01|2021-06-07
>hCoV-19/USA/IN-INSPHL-02095/2021|2021-06-04|2021-06-07

sequence ids in abundance.tsv are the same as in fasta file (with dates added), and therefore to make output_abundances.py script to work an intermediate step of splitting sequence id in the abundance file is required (not a big problem, but thought I mention it here).  

Everything else works great! Thank you!

**Comment by jbaaijens** [comment]
Hi @irinak128, thank you for your feedback. Did this error occur with the most recent version of the script `pipeline/output_abundances.py`? This naming issue is due to changes in GISAID metadata formatting, but it should be fixed in the updated scripts.

**Comment by irinak128** [comment]
For me it was happening from when I first tried your scripts it in the end  of September and still the same using scripts from pull as of 11-12. So seems it is still there. I simply use one extra step of splitting first column in the abundance.tsv by "|", making abundanceMod.tsv and then use that file in following output_abundances.py script

**Comment by jbaaijens** [comment]
Thanks, I'll look into it.

**Comment by irinak128** [comment]
could this be related? (sorry, I am not that good in python):

lines 121 and 122 in the preprocess_references.py
      # seq_id = line.rstrip('\n').lstrip('>').split('|')[0]
         seq_id = line.rstrip('\n').lstrip('>').split()[0]

**Comment by jbaaijens** [comment]
Yes, this is also related to the GISAID reformatting, it affects our pipeline at multiple points. However, I've been able to run the pipeline without any issues since I made the last updates (november 2nd). Are you sure you are using the latest version of `pipeline/output_abundances.py`? It should have `seqname = line[0].split('|')[0]` (line 70) which fixes the issue you described.

**Comment by irinak128** [comment]
You are right - it works perfectly now from abundance.tsv ! Sorry for the false alarm!
I just checked sequences.fasta headers  and abundance.tsv sequence-ids with new scripts and saw longer names and assumed I still need extra step of splitting. Just tried running output_abundances.py directly from abundance.tsv and it works perfectly fine.

Sorry again for the false claim. And thanks again for your scripts!
